services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Madj2k\CatSearch\:
    resource: '../Classes/*'

  Madj2k\CatSearch\Hooks\TCEMainHook:
    public: true

  cache.catsearch_filteroptions:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'catsearch_filteroptions' ]

  Madj2k\CatSearch\Controller\SearchController:
    calls:
      - method: 'injectCache'
        arguments:
          $cache: '@cache.catsearch_filteroptions'
